Repository fractal-academy/pdp-app, pull requests merged in 2021-03, with the labels that each got.

#15 rename filter to viewFor
  src/app/domains/User/components/tables/UserSimpleTable/UserSimpleTable.stories.js
  src/app/domains/User/components/tables/UserSimpleTable/UserSimpleTable.template.js
Labels: fix

#16 created userAvdTable, fixed userSmplTable
  src/app/domains/User/components/tables/UserAdvancedTable/UserAdvancedTable.stories.js
  src/app/domains/User/components/tables/UserAdvancedTable/UserAdvancedTable.template.js
  src/app/domains/User/components/tables/UserSimpleTable/UserSimpleTable.template.js
Labels: fix, layout

#18 added competenceSmplView
  src/app/domains/Competence/components/views/CompetenceSimpleView/CompetenceSimpleView.stories.js
  src/app/domains/Competence/components/views/CompetenceSimpleView/CompetenceSimpleView.template.js
Labels: layout

#19 added level adv and smpl views
  src/app/domains/Level/components/views/LevelAdvancedView/LevelAdvancedView.stories.js
  src/app/domains/Level/components/views/LevelAdvancedView/LevelAdvancedView.template.js
  src/app/domains/Level/components/views/LevelSimpleView/LevelSimpleView.stories.js
  src/app/domains/Level/components/views/LevelSimpleView/LevelSimpleView.template.js
Labels: layout

#17 added skillSmplView
  src/app/domains/Skill/components/views/SkillSimpleView/SkillSimpleView.stories.js
  src/app/domains/Skill/components/views/SkillSimpleView/SkillSimpleView.template.js
Labels: layout

#20 Navigations panel
  .eslintrc.js
  craco.config.js
  jsconfig.json
  package.json
  public/index.html
  src/app/constants/routePaths.js
  src/app/constants/routes.js
  src/app/contexts/Session/components/Provider/Provider.js
  src/app/contexts/Session/components/Provider/index.js
  src/app/contexts/Session/components/index.js
  src/app/contexts/Session/constants/index.js
  src/app/contexts/Session/constants/types.js
  src/app/contexts/Session/context.js
  src/app/contexts/Session/hooks/index.js
  src/app/contexts/Session/hooks/useSession.js
  src/app/contexts/Session/hooks/useSessionDispatch.js
  src/app/contexts/Session/index.js
  src/app/contexts/Session/reducer.js
  src/app/domains/User/components/views/UserAdvancedView/UserAdvancedView.template.js
  src/app/index.js
  src/components/Navigation/Navigation.style.js
  src/components/Navigation/Navigation.template.js
  src/config/theme/antdStyled.js
  src/config/theme/index.js
  src/index.js
  src/modules/chat-module/constants/routes.js
  src/modules/chat-module/index.js
Labels: layout, logic

#21 Connect availible routes
  src/app/domains/User/components/tables/UserAdvancedTable/UserAdvancedTable.template.js
  src/app/domains/User/routes/UserAll/UserAll.layout.js
  src/app/index.js
Labels: layout

#22 technology simple view
  src/app/domains/Technology/components/views/TechnologySimpleView/TechnologySimpleView.stories.js
  src/app/domains/Technology/components/views/TechnologySimpleView/TechnologySimpleView.template.js
Labels: layout

#23 Role select refactoring
  src/app/contexts/Role/components/Provider/Provider.js
  src/app/contexts/Role/components/Provider/index.js
  src/app/contexts/Role/components/index.js
  src/app/contexts/Role/context.js
  src/app/contexts/Role/hooks/index.js
  src/app/contexts/Role/hooks/useRole.js
  src/app/contexts/Session/components/Provider/Provider.js
  src/app/contexts/Session/constants/types.js
  src/app/contexts/Session/reducer.js
  src/app/domains/Role/components/selects/RoleSingleSelect/RoleSingleSelect.template.js
  src/app/domains/User/components/views/UserAdvancedView/UserAdvancedView.template.js
  src/components/Navigation/Navigation.template.js
  src/index.js
Labels: layout, refactor

#24 Technology adv view
  src/app/domains/Skill/components/views/SkillSimpleView/SkillSimpleView.template.js
  src/app/domains/Technology/components/views/TechnologyAdvancedView/TechnologyAdvancedView.stories.js
  src/app/domains/Technology/components/views/TechnologyAdvancedView/TechnologyAdvancedView.template.js
  src/app/domains/Technology/components/views/TechnologySimpleView/TechnologySimpleView.template.js
Labels: fix, layout

#26 added technology simple list
  src/app/domains/Technology/components/lists/TechnologySimpleList/TechnologySimpleList.stories.js
  src/app/domains/Technology/components/lists/TechnologySimpleList/TechnologySimpleList.template.js
Labels: layout

#27 Added technology simple list to route
  src/app/domains/Technology/routes/TechnologyAll/TechnologyAll.layout.js
Labels: layout

#28 Added access denied component layout
  src/assets/access_denied.svg
  src/components/AccessDenied/AccessDenied.template.js
Labels: layout

#29 added skill select
  src/app/domains/Skill/components/selects/SkillSingleSelect/SkillSingleSelect.stories.js
  src/app/domains/Skill/components/selects/SkillSingleSelect/SkillSingleSelect.style.js
  src/app/domains/Skill/components/selects/SkillSingleSelect/SkillSingleSelect.template.js
Labels: layout

#30 Not found path
  src/app/contexts/Role/hooks/useRole.js
  src/assets/page_not_found.svg
  src/components/NotFoundPath/NotFoundPath.template.js
Labels: documentation, layout

#31 fixed skill select
  src/app/domains/Skill/components/selects/SkillSingleSelect/SkillSingleSelect.template.js
Labels: fix

#32 Fix navigation
  package.json
  src/app/constants/routes.js
  src/app/contexts/Role/components/Provider/Provider.js
  src/app/contexts/Role/hooks/useRole.js
  src/app/domains/Role/components/selects/RoleSingleSelect/RoleSingleSelect.template.js
  src/app/domains/User/components/views/UserAdvancedView/UserAdvancedView.template.js
  src/components/HOC/index.js
  src/components/HOC/withProtect/index.js
  src/components/HOC/withProtect/withProtect.js
  src/components/Navigation/Navigation.template.js
  src/config/theme/antdStyled.js
  src/modules/chat-module/constants/routePaths.js
  src/modules/chat-module/constants/routes.js
Labels: fix, layout, logic

#33 Fixed navigations menu bug: when go to another role path, didn't set it
  src/components/HOC/withProtect/withProtect.js
Labels: fix, logic

#34 added level single select, fixed prettier in techSingleSelect
  src/app/domains/Level/components/selects/LevelSingleSelect/LevelSingleSelect.stories.js
  src/app/domains/Level/components/selects/LevelSingleSelect/LevelSingleSelect.style.js
  src/app/domains/Level/components/selects/LevelSingleSelect/LevelSingleSelect.template.js
  src/app/domains/Technology/components/selects/TechnologySingleSelect/TechnologySingleSelect.stories.js
Labels: layout

#35 created level single select, fixed level simple view
  src/app/domains/Level/components/combined/tree/LevelTreeSingleSelect/LevelTreeSingleSelect.stories.js
  src/app/domains/Level/components/combined/tree/LevelTreeSingleSelect/LevelTreeSingleSelect.style.js
  src/app/domains/Level/components/combined/tree/LevelTreeSingleSelect/LevelTreeSingleSelect.template.js
  src/app/domains/Level/components/views/LevelSimpleView/LevelSimpleView.template.js
Labels: fix, layout

#39 Todo list creation
  src/app/constants/routes.js
  src/app/domains/Technology/components/lists/TechnologySimpleList/TechnologySimpleList.stories.js
  src/app/domains/Technology/routes/TechnologyAll/TechnologyAll.layout.js
  src/app/domains/Todo/components/forms/TodoSimpleForm/TodoSimpleForm.template.js
  src/app/domains/Todo/components/lists/TodoSimpleList/TodoSimpleList.template.js
  src/app/domains/Todo/routes/TodoCreate/TodoCreate.layout.js
  src/app/index.js
  src/components/HOC/index.js
  src/components/HOC/withContent/index.js
  src/components/HOC/withContent/withContent.js
  src/components/HOC/withProtect/withProtect.js
Labels: layout, logic

#40 Interview create
  src/app/constants/routes.js
  src/app/domains/Interview/components/forms/InterviewSimpleForm/InterviewSimpleForm.template.js
  src/app/domains/Interview/components/lists/InterviewSimpleList/InterviewSimpleList.template.js
  src/app/domains/Interview/routes/InterviewCreate/InterviewCreate.layout.js
  src/app/domains/Technology/routes/TechnologyCreate/TechnologyCreate.layout.js
Labels: layout

#43 Fixed redirection, wrapped in content chat module routes, Added basic…
  src/app/domains/Plan/routes/PlanAll/PlanAll.layout.js
  src/app/index.js
  src/modules/chat-module/constants/routes.js
Labels: fix

#45 Materials list wizard
  package.json
  src/app/domains/Material/components/combined/lists/MaterialListsWithUpload/MaterialListsWithUpload.stories.js
  src/app/domains/Material/components/combined/lists/MaterialListsWithUpload/MaterialListsWithUpload.template.js
  src/app/domains/Material/components/combined/lists/MaterialListsWithUpload/__tests__/MaterialListsWithUpload.test.js
  src/app/domains/Material/components/combined/lists/MaterialListsWithUpload/index.js
  src/app/domains/Material/components/combined/lists/index.js
  src/app/domains/Material/components/combined/uploads/MaterialSimpleUpload/MaterialSimpleUpload.stories.js
  src/app/domains/Material/components/combined/uploads/MaterialSimpleUpload/MaterialSimpleUpload.template.js
  src/app/domains/Material/components/combined/uploads/MaterialSimpleUpload/__tests__/MaterialSimpleUpload.test.js
  src/app/domains/Material/components/combined/uploads/MaterialSimpleUpload/index.js
  src/app/domains/Material/components/combined/uploads/index.js
  src/app/domains/Material/components/forms/MaterialSimpleForm/MaterialSimpleForm.stories.js
  src/app/domains/Material/components/forms/MaterialSimpleForm/MaterialSimpleForm.template.js
  src/app/domains/Material/components/forms/MaterialSimpleForm/__tests__/MaterialSimpleForm.test.js
  src/app/domains/Material/components/forms/MaterialSimpleForm/index.js
  src/app/domains/Material/components/forms/index.js
  src/app/domains/Material/components/lists/MaterialSimpleList/MaterialSimpleList.template.js
  src/app/domains/Material/components/views/MaterialSimpleView/MaterialSimpleView.template.js
  src/app/domains/Material/routes/MaterialCreate/MaterialCreate.layout.js
  src/components/AccessDenied/AccessDenied.template.js
  src/components/Navigation/Navigation.template.js
  src/components/NotFoundPath/NotFoundPath.template.js
  src/services/Firebase/storage/index.js
Labels: layout, logic

#48 Competence adv view
  src/app/domains/Competence/components/lists/CompetenceSimpleList/CompetenceSimpleList.stories.js
  src/app/domains/Competence/components/lists/CompetenceSimpleList/CompetenceSimpleList.template.js
  src/app/domains/Competence/components/views/CompetenceAdvancedView/CompetenceAdvancedView.stories.js
  src/app/domains/Competence/components/views/CompetenceAdvancedView/CompetenceAdvancedView.template.js
  src/app/domains/Competence/components/views/CompetenceSimpleView/CompetenceSimpleView.template.js
  src/app/domains/Competence/routes/CompetenceAll/CompetenceAll.layout.js
  src/app/domains/Level/components/selects/LevelSingleSelect/LevelSingleSelect.template.js
  src/app/domains/Technology/components/combined/cascader/TechnologyAdvancedCascader/TechnologyAdvancedCascader.stories.js
  src/app/domains/Technology/components/views/TechnologyAdvancedView/TechnologyAdvancedView.template.js
  src/app/domains/Technology/components/views/TechnologySimpleView/TechnologySimpleView.stories.js
  src/app/domains/Technology/components/views/TechnologySimpleView/TechnologySimpleView.template.js
  src/components/Spinner/Spinner.template.js
  src/components/Spinner/index.js
  src/components/index.js
Labels: fix, layout

#49 added get grid function
  src/app/domains/Competence/components/lists/CompetenceSimpleList/CompetenceSimpleList.template.js
  src/utils/getGrid.js
  src/utils/index.js
Labels: layout

#50 Fixed bugs and extended PageWrapper
  src/app/constants/routes.js
  src/app/domains/Material/components/combined/uploads/MaterialSimpleUpload/MaterialSimpleUpload.template.js
  src/components/HOC/PageWrapper/PageWrapper.js
Labels: fix

#51 Interview create
  src/app/domains/Technology/components/forms/TechnologyAdvancedForm/TechnologyAdvancedForm.template.js
  src/app/domains/Technology/routes/TechnologyCreate/TechnologyCreate.layout.js
  src/components/HOC/PageWrapper/PageWrapper.js
Labels: fix

#52 added pageTitle component
  src/app/domains/Technology/routes/TechnologyAll/TechnologyAll.layout.js
  src/components/PageTitle/PageTitle.template.js
  src/components/PageTitle/index.js
  src/components/index.js
Labels: layout

#53 added goBack function to PageTitle
  src/components/PageTitle/PageTitle.template.js
Labels: fix

#54 Added new properties to PageWrapper component
  src/components/HOC/PageWrapper/PageWrapper.js
Labels: documentation, fix, layout, logic

#55 Creation plan wizard
  craco.config.js
  src/app/constants/routes.js
  src/app/domains/Plan/components/views/PlanAdvancedView/PlanAdvancedView.stories.js
  src/app/domains/Plan/components/views/PlanAdvancedView/PlanAdvancedView.template.js
  src/app/domains/Plan/components/views/PlanAdvancedView/__tests__/PlanAdvancedView.test.js
  src/app/domains/Plan/components/views/PlanAdvancedView/index.js
  src/app/domains/Plan/components/views/index.js
  src/app/domains/Plan/routes/PlanCreate/PlanCreate.layout.js
  src/app/domains/Student/components/tables/StudentSimpleTable/StudentSimpleTable.template.js
  src/app/domains/Student/routes/StudentAll/StudentAll.layout.js
  src/app/domains/Todo/components/lists/TodoSimpleList/TodoSimpleList.template.js
  src/app/domains/User/routes/UserShow/UserShow.layout.js
Labels: layout, refactor

#56 Plan
  package.json
  src/app/contexts/Session/components/Provider/Provider.js
  src/app/domains/Material/components/lists/MaterialSimpleList/MaterialSimpleList.template.js
  src/app/domains/Material/components/views/MaterialSimpleView/MaterialSimpleView.template.js
  src/app/domains/Plan/components/lists/PlanSimpleList/PlanSimpleList.template.js
  src/app/domains/Plan/components/views/PlanAdvancedView/PlanAdvancedView.template.js
  src/app/domains/Plan/components/views/PlanSimpleView/PlanSimpleView.stories.js
  src/app/domains/Plan/components/views/PlanSimpleView/PlanSimpleView.template.js
  src/app/domains/Plan/routes/PlanAll/PlanAll.layout.js
  src/app/domains/Technology/components/views/TechnologyAdvancedView/TechnologyAdvancedView.template.js
  src/app/domains/Technology/components/views/TechnologySimpleView/TechnologySimpleView.template.js
  src/components/Status/Status.style.js
  src/components/Status/Status.template.js
  src/components/Status/index.js
  src/components/index.js
Labels: fix, layout, refactor

#57 Loading to pages
  src/app/domains/Company/components/views/CompanySimpleView/CompanySimpleView.stories.js
  src/app/domains/Company/components/views/CompanySimpleView/CompanySimpleView.template.js
  src/app/domains/Competence/components/views/CompetenceSimpleView/CompetenceSimpleView.stories.js
  src/app/domains/Competence/components/views/CompetenceSimpleView/CompetenceSimpleView.template.js
  src/app/domains/Plan/components/lists/PlanSimpleList/PlanSimpleList.template.js
  src/app/domains/Plan/components/views/PlanAdvancedView/PlanAdvancedView.template.js
  src/app/domains/Plan/components/views/PlanSimpleView/PlanSimpleView.template.js
  src/app/domains/Plan/routes/PlanAll/PlanAll.layout.js
  src/app/domains/Student/components/tables/StudentSimpleTable/StudentSimpleTable.template.js
  src/app/domains/Technology/components/lists/TechnologySimpleList/TechnologySimpleList.template.js
  src/app/domains/Technology/components/views/TechnologyAdvancedView/TechnologyAdvancedView.template.js
  src/app/domains/Technology/components/views/TechnologySimpleView/TechnologySimpleView.template.js
Labels: fix

#59 Sider todo list
  src/app/domains/Plan/components/lists/PlanSimpleList/PlanSimpleList.template.js
  src/app/domains/Plan/components/views/PlanAdvancedView/PlanAdvancedView.template.js
  src/app/domains/Plan/components/views/PlanSimpleView/PlanSimpleView.template.js
  src/app/domains/Plan/routes/PlanAll/PlanAll.layout.js
  src/app/domains/Technology/components/lists/TechnologyAdvancedList/TechnologyAdvancedList.stories.js
  src/app/domains/Technology/components/lists/TechnologyAdvancedList/TechnologyAdvancedList.template.js
  src/app/domains/Technology/components/lists/TechnologyAdvancedList/__tests__/TechnologyAdvancedList.test.js
  src/app/domains/Technology/components/lists/TechnologyAdvancedList/index.js
  src/app/domains/Technology/components/lists/TechnologySimpleList/TechnologySimpleList.template.js
  src/app/domains/Technology/components/lists/index.js
  src/app/domains/Technology/components/views/TechnologyAdvancedView/TechnologyAdvancedView.template.js
  src/app/domains/Technology/routes/TechnologyAll/TechnologyAll.layout.js
  src/app/domains/Todo/components/combined/views/TodoViewWIthActions/TodoViewWIthActions.template.js
  src/app/domains/Todo/components/lists/TodoAdvancesList/TodoAdvancedList.stories.js
  src/app/domains/Todo/components/lists/TodoAdvancesList/TodoAdvancedList.template.js
  src/app/domains/Todo/components/lists/TodoAdvancesList/__tests__/TodoAdvancedList.test.js
  src/app/domains/Todo/components/lists/TodoAdvancesList/index.js
  src/app/domains/Todo/components/lists/index.js
Labels: fix, layout, logic, refactor

#60 fixed condition
  src/app/domains/Todo/components/lists/TodoAdvancesList/TodoAdvancedList.template.js
Labels: fix

#61 Fixed routing, fixed technology list error
  src/app/constants/routes.js
  src/app/domains/Technology/components/lists/TechnologyAdvancedList/TechnologyAdvancedList.template.js
  src/app/domains/Technology/components/lists/TechnologySimpleList/TechnologySimpleList.template.js
  src/app/index.js
Labels: fix

#62 added sessionSmplForm, Login and Register layout
  src/app/domains/Session/components/forms/SessionSimpleForm/SessionSimpleForm.template.js
  src/app/domains/Session/routes/SessionLogin/SessionLogin.layout.js
  src/app/domains/Session/routes/SessionRegister/SessionRegister.layout.js
Labels: layout

#63 Services
  src/services/Firebase/firestore/getCollectionData.js
  src/services/Firebase/firestore/getDocumentData.js
  src/services/Firebase/firestore/index.js
Labels: documentation, logic

#65 fix getCollectionData
  src/services/Firebase/firestore/getCollectionData.js
Labels: fix

#66 Session
  src/app/contexts/Session/components/Provider/Provider.js
  src/app/contexts/Session/reducer.js
  src/app/contexts/Session/types.js
  src/app/domains/Plan/components/lists/PlanSimpleList/PlanSimpleList.template.js
  src/app/domains/Plan/routes/PlanAll/PlanAll.layout.js
  src/app/domains/Session/components/forms/SessionSimpleForm/SessionSimpleForm.template.js
  src/app/index.js
  src/components/Navigation/Navigation.template.js
  src/hooks/auth/index.js
  src/hooks/auth/useAuthListener.js
  src/hooks/index.js
  src/index.js
  src/services/Firebase/auth/index.js
Labels: fix, logic

#69 Session
  src/app/index.js
  src/components/Navigation/Navigation.template.js
  src/hooks/auth/useAuthListener.js
Labels: layout, logic

#58 Technology create wizard
  src/app/constants/collections.js
  src/app/domains/Interview/components/forms/InterviewSimpleForm/InterviewSimpleForm.template.js
  src/app/domains/Interview/components/lists/InterviewSimpleList/InterviewSimpleList.template.js
  src/app/domains/Interview/routes/InterviewCreate/InterviewCreate.layout.js
  src/app/domains/Level/components/combined/modals/LevelModalWithForm/LevelModalWithForm.stories.js
  src/app/domains/Level/components/combined/modals/LevelModalWithForm/LevelModalWithForm.template.js
  src/app/domains/Level/components/combined/modals/LevelModalWithForm/__tests__/LevelModalWithForm.test.js
  src/app/domains/Level/components/combined/modals/LevelModalWithForm/index.js
  src/app/domains/Level/components/combined/modals/index.js
  src/app/domains/Level/components/combined/selects/LevelSelectWithCreate/LevelSelectWithCreate.stories.js
  src/app/domains/Level/components/combined/selects/LevelSelectWithCreate/LevelSelectWithCreate.template.js
  src/app/domains/Level/components/combined/selects/LevelSelectWithCreate/__tests__/LevelSelectWithCreate.test.js
  src/app/domains/Level/components/combined/selects/LevelSelectWithCreate/index.js
  src/app/domains/Level/components/combined/selects/index.js
  src/app/domains/Level/components/forms/LevelSimpleForm/LevelSimpleForm.template.js
  src/app/domains/Material/components/forms/MaterialSimpleForm/MaterialSimpleForm.template.js
  src/app/domains/Material/routes/MaterialCreate/MaterialCreate.layout.js
  src/app/domains/Question/components/combined/views/QuestionViewWithForm/QuestionViewWithForm.template.js
  src/app/domains/Question/components/forms/QuestionSimpleForm/QuestionSimpleForm.template.js
  src/app/domains/Question/components/views/QuestionSimpleView/QuestionSimpleView.template.js
  src/app/domains/Role/components/selects/RoleSingleSelect/RoleSingleSelect.template.js
  src/app/domains/Skill/components/selects/SkillSingleSelect/SkillSingleSelect.template.js
  src/app/domains/Technology/components/combined/cascader/TechnologyAdvancedCascader/TechnologyAdvancedCascader.template.js
  src/app/domains/Technology/components/forms/TechnologyAdvancedForm/TechnologyAdvancedForm.template.js
  src/app/domains/Technology/components/lists/TechnologySimpleList/TechnologySimpleList.template.js
  src/app/domains/Technology/components/views/TechnologyAdvancedView/TechnologyAdvancedView.template.js
  src/app/domains/Technology/routes/TechnologyCreate/TechnologyCreate.layout.js
  src/app/domains/Todo/components/combined/views/TodoViewWIthActions/TodoViewWIthActions.stories.js
  src/app/domains/Todo/components/forms/TodoSimpleForm/TodoSimpleForm.template.js
  src/app/domains/Todo/components/lists/TodoSimpleList/TodoSimpleList.template.js
  src/app/domains/Todo/routes/TodoCreate/TodoCreate.layout.js
  src/app/domains/Type/components/selects/TypeSingleSelect/TypeSingleSelect.stories.js
  src/app/domains/Type/components/selects/TypeSingleSelect/TypeSingleSelect.template.js
  src/app/domains/Type/components/selects/TypeSingleSelect/__tests__/TypeSingleSelect.test.js
  src/app/domains/Type/components/selects/TypeSingleSelect/index.js
  src/app/domains/Type/components/selects/index.js
  src/components/Navigation/Navigation.style.js
  src/components/Navigation/Navigation.template.js
  src/constants/index.js
  src/constants/skills.js
  src/constants/types.js
  src/services/Firebase/firestore/getDocumentData.js
  src/services/Firebase/firestore/getDocumentRef.js
  src/services/Firebase/firestore/getTimestamp.js
  src/services/Firebase/firestore/index.js
  src/services/Firebase/firestore/updateDocument.js
Labels: documentation, fix, layout, logic, refactor

#70 Implemented level preset delete functions
  src/app/domains/Level/components/combined/modals/LevelModalWithForm/LevelModalWithForm.template.js
  src/app/domains/Level/components/combined/selects/LevelSelectWithCreate/LevelSelectWithCreate.template.js
Labels: logic

#71 Session
  src/app/domains/Student/components/tables/StudentSimpleTable/StudentSimpleTable.template.js
  src/app/domains/User/components/tables/UserSimpleTable/UserSimpleTable.template.js
  src/app/domains/User/components/views/UserSimpleView/UserSimpleView.template.js
  src/app/domains/User/routes/UserAll/UserAll.layout.js
  src/app/domains/User/routes/UserShow/UserShow.layout.js
  src/components/Navigation/Navigation.template.js
  src/hooks/auth/useAuthListener.js
Labels: fix, logic

#73 Fixed redirection bug, a lot of small fixes
  src/app/domains/Session/routes/SessionLogin/SessionLogin.layout.js
  src/app/domains/Session/routes/SessionRegister/SessionRegister.layout.js
  src/app/domains/User/components/views/UserAdvancedView/UserAdvancedView.template.js
  src/app/domains/User/routes/UserShow/UserShow.layout.js
  src/app/index.js
  src/components/Navigation/Navigation.template.js
  src/hooks/auth/useAuthListener.js
Labels: fix, logic

#74 Edit profile
  package.json
  src/app/domains/Role/components/selects/RoleSingleSelect/RoleSingleSelect.template.js
  src/app/domains/User/components/combined/modals/UserModalWithForm/UserModalWithForm.template.js
  src/app/domains/User/components/forms/UserSimpleForm/UserSimpleForm.template.js
  src/app/domains/User/components/views/UserAdvancedView/UserAdvancedView.template.js
  src/app/domains/User/components/views/UserSimpleView/UserSimpleView.template.js
  src/app/domains/User/routes/UserAll/UserAll.layout.js
  src/app/domains/User/routes/UserShow/UserShow.layout.js
  src/components/Navigation/Navigation.template.js
  src/hooks/auth/useAuthListener.js
  src/services/Firebase/storage/deleteURL.js
  src/services/Firebase/storage/getURL.js
  src/services/Firebase/storage/index.js
  src/services/Firebase/storage/storageReference.js
  src/services/Firebase/storage/upload.js
Labels: fix, layout, logic

#75 added document in students collection in proccess sign in
  src/hooks/auth/useAuthListener.js
Labels: fix

#77 fixed loading to storage
  src/app/domains/User/components/forms/UserSimpleForm/UserSimpleForm.template.js
Labels: fix

#78 added condition for first user (admin)
  src/hooks/auth/useAuthListener.js
Labels: fix

#79 User show
  src/app/domains/Company/components/lists/CompanySimpleList/CompanySimpleList.template.js
  src/app/domains/Company/components/views/CompanySimpleView/CompanySimpleView.template.js
  src/app/domains/Mentor/components/tables/MentorSimpleTable/MentorSimpleTable.template.js
  src/app/domains/Student/components/tables/StudentSimpleTable/StudentSimpleTable.template.js
  src/app/domains/User/components/combined/modals/UserModalWithForm/UserModalWithForm.template.js
  src/app/domains/User/components/forms/UserSimpleForm/UserSimpleForm.template.js
  src/app/domains/User/components/views/UserAdvancedView/UserAdvancedView.template.js
  src/app/domains/User/components/views/UserSimpleView/UserSimpleView.template.js
  src/services/Firebase/firestore/getCollectionRef.js
  src/services/Firebase/firestore/index.js
  src/utils/index.js
  src/utils/mergeUserData.js
Labels: fix, layout

#80 Implemented level cascader & refactored technology create component
  src/app/domains/Level/components/combined/cascaders/LevelSimpleCascader/LevelSimpleCascader.stories.js
  src/app/domains/Level/components/combined/cascaders/LevelSimpleCascader/LevelSimpleCascader.template.js
  src/app/domains/Level/components/combined/cascaders/LevelSimpleCascader/__tests__/LevelSimpleCascader.test.js
  src/app/domains/Level/components/combined/cascaders/LevelSimpleCascader/index.js
  src/app/domains/Level/components/combined/cascaders/index.js
  src/app/domains/Technology/routes/TechnologyCreate/TechnologyCreate.layout.js
Labels: logic, refactor

#81 fix useAuthListener
  src/app/domains/User/components/combined/modals/UserModalWithForm/UserModalWithForm.template.js
  src/app/domains/User/components/forms/UserSimpleForm/UserSimpleForm.template.js
  src/app/domains/User/routes/UserShow/UserShow.layout.js
  src/hooks/auth/useAuthListener.js
Labels: fix

#84 merged data for user + student and mentor in context
  src/app/contexts/Session/reducer.js
  src/hooks/auth/useAuthListener.js
Labels: fix

#82 craeted CompanyMltplSelect
  src/app/domains/Company/components/selects/CompanyMultipleSelect/CompanyMultipleSelect.stories.js
  src/app/domains/Company/components/selects/CompanyMultipleSelect/CompanyMultipleSelect.template.js
  src/app/domains/Company/components/selects/CompanyMultipleSelect/__tests__/CompanyMultipleSelect.test.js
  src/app/domains/Company/components/selects/CompanyMultipleSelect/index.js
  src/app/domains/Company/components/selects/index.js
  src/app/domains/User/components/combined/modals/UserModalWithForm/UserModalWithForm.template.js
  src/app/domains/User/components/forms/UserSimpleForm/UserSimpleForm.template.js
  src/app/domains/User/routes/UserShow/UserShow.layout.js
Labels: layout, logic

#85 Fix button loading
  src/app/domains/User/components/combined/modals/UserModalWithForm/UserModalWithForm.template.js
Labels: fix

#86 User show
  src/app/contexts/Session/components/Provider/Provider.js
  src/app/domains/User/components/combined/modals/UserModalWithForm/UserModalWithForm.template.js
  src/app/domains/User/components/forms/UserSimpleForm/UserSimpleForm.template.js
  src/app/domains/User/routes/UserShow/UserShow.layout.js
  src/components/Navigation/Navigation.template.js
  src/hooks/auth/useAuthListener.js
Labels: fix, layout

#88 changed field`s name
  src/app/domains/Plan/routes/PlanAll/PlanAll.layout.js
Labels: fix

#90 Plan wizard
  src/app/domains/Interview/components/lists/InterviewSimpleList/InterviewSimpleList.template.js
  src/app/domains/Interview/routes/InterviewCreate/InterviewCreate.layout.js
  src/app/domains/Plan/components/forms/PlanSimpleForm/PlanSimpleForm.js
  src/app/domains/Plan/components/forms/PlanSimpleForm/index.js
  src/app/domains/Plan/components/forms/index.js
  src/app/domains/Plan/routes/PlanCreate/PlanCreate.layout.js
  src/app/domains/Question/components/combined/views/QuestionViewWithForm/QuestionViewWithForm.template.js
  src/app/domains/Todo/routes/TodoCreate/TodoCreate.layout.js
  src/app/domains/User/routes/UserShow/UserShow.layout.js
  src/components/Spinner/Spinner.template.js
  src/hooks/auth/useAuthListener.js
Labels: fix, layout, logic, refactor

#91 created card with plans in student`s profile
  src/app/domains/Plan/routes/PlanAll/PlanAll.layout.js
  src/app/domains/User/routes/UserShow/UserShow.layout.js
Labels: fix

#93 Interview edit
  src/app/constants/routes.js
  src/app/domains/Interview/routes/InterviewEdit/InterviewEdit.layout.js
  src/app/domains/User/routes/UserShow/UserShow.layout.js
  src/components/Status/Status.template.js
Labels: fix, layout

#94 added condition for Button
  src/app/domains/User/routes/UserShow/UserShow.layout.js
Labels: layout

#99 fixed plan create
  src/app/domains/Plan/routes/PlanCreate/PlanCreate.layout.js
Labels: fix, layout

#103 changed useCollArray to useColData with condition
  src/app/domains/Todo/components/lists/TodoAdvancesList/TodoAdvancedList.template.js
Labels: fix

#105 deleted border from collapse
  src/hooks/auth/useAuthListener.js
  src/styles/index.less
Labels: fix

#110 Interview to menu
  src/app/domains/Interview/routes/InterviewAll/InterviewAll.layout.js
  src/app/domains/Technology/components/views/TechnologyAdvancedView/TechnologyAdvancedView.template.js
  src/app/domains/Todo/components/lists/TodoAdvancesList/TodoAdvancedList.template.js
Labels: fix
